import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800']
});

export const metadata = {
  title: "Link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={poppins.className}>
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1 flex justify-start items-start gap-6">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
